services:
  calendar:
    build: .
    command: sh -c 'alembic upgrade head && python main.py'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./logs:/app/logs:cached
      - ./alembic:/app/alembic
      - ./src:/app/src
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data:cached


volumes:
  db-data:
