services:
  calendar:
    build: src
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:cached
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data:cached


volumes:
  db-data:
