"""Create databases

Revision ID: 0a43eadc15bb
Revises: 
Create Date: 2022-05-09 05:51:27.935444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from create_db import import_dump_for_alembic


# revision identifiers, used by Alembic.
revision = '0a43eadc15bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    event = op.create_table('event',
    sa.Column('start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aud', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teachers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_names', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    student = op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    calendar = op.create_table('calendar',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'event_id')
    )
    students, events, calendars = import_dump_for_alembic()
    op.bulk_insert(student, students)
    op.bulk_insert(event, events)
    op.bulk_insert(calendar, calendars)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    op.drop_table('student')
    op.drop_table('event')
    # ### end Alembic commands ###
