"""event_id rels to bigint

Revision ID: 27a646cd2448
Revises: 3910f5594e06
Create Date: 2022-10-18 21:38:46.635471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '27a646cd2448'
down_revision = '3910f5594e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'event_id', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar', 'event_id', existing_type=sa.BigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
