"""event_id to bigint

Revision ID: 3910f5594e06
Revises: 0a43eadc15bb
Create Date: 2022-10-18 21:17:02.716238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3910f5594e06'
down_revision = '0a43eadc15bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'id', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'id', existing_type=sa.BigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
